const router = require('express').Router()

const auth = require('~/routes/auth')
const user = require('~/routes/user')
const email = require('~/routes/email')
const adminInvitation = require('~/routes/adminInvitation')
const question = require('~/routes/question')
const resourcesCategory = require('~/routes/resourcesCategory')
const offer = require('~/routes/offer')
const location = require('~/routes/location')
const subjects = require('~/routes/subjects')
const categories = require('~/routes/categories')
const uploadAvatar = require('~/routes/uploadAvatar')
const lessons = require('~/routes/lessons')

router.use('/auth', auth)
router.use('/users', user)
router.use('/send-email', email)
router.use('/admin-invitations', adminInvitation)
router.use('/questions', question)
router.use('/resources-categories', resourcesCategory)
router.use('/offers', offer)
router.use('/locations', location)
router.use('/api/subjects', subjects)
router.use('/api/categories', categories)
router.use('/tutor', uploadAvatar)
router.use('/lessons', lessons)

module.exports = router
